### PR TITLE
initialized express server, added package-lock.json

### PR DESCRIPTION
**Pull request by TheBigBooler**
Created initial express server, added package-lock.json to install modules, and created index.js file

### CODE REVIEW

**Review by casecn — CHANGES_REQUESTED** [review]
Has this successfully ran on your local host.  

Add script to run script.

**Comment by TheBigBooler** [comment]
Added "start" and "start:dev" scripts, tested server on localhost:3000

**Review by casecn — APPROVED** [review]
Looks good to me

**Review by hmvassar — APPROVED** [review]
Everything looks good.

**Pull request merged**
